using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data.Entity;

namespace MvcSeasonsSite.Models
{
    public class SeasonSiteInitializer : DropCreateDatabaseIfModelChanges<SeasonSiteContext>
    {
        protected override void Seed(SeasonSiteContext context)
        {
            var Specials = new Special()
                {
                    Content = @"

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Maecenas consequat cursus ultricies. Ut urna ipsum, blandit id sollicitudin eu, feugiat vel justo. Praesent pulvinar, diam vel dapibus accumsan, velit est varius massa, nec malesuada purus nibh in risus. Cras blandit lectus eget risus dictum a accumsan lacus consectetur. Pellentesque non ligula est. Vivamus hendrerit fringilla lacus, vitae feugiat turpis gravida nec. Donec egestas volutpat ultricies. Quisque ultrices quam eros, sit amet sodales risus. Praesent lobortis dignissim nunc sed consectetur.

Mauris hendrerit pulvinar laoreet. Donec viverra congue vehicula. Aliquam porta leo vel ipsum vestibulum tincidunt. Pellentesque nec felis nibh. Ut hendrerit odio eu felis tempus ut volutpat risus adipiscing. In vel leo lacus, vitae pellentesque est. Donec molestie blandit purus, at egestas diam dignissim ac. Nulla volutpat nisi sed sem aliquam scelerisque a id ante. Aenean sed leo eros, in gravida libero. Aenean accumsan ornare eros, quis scelerisque purus varius in. Nunc laoreet, sem sit amet pulvinar gravida, elit ante faucibus magna, eget pharetra tortor mi non nisl. Praesent volutpat orci ut tellus blandit tempus. Pellentesque scelerisque dignissim nulla suscipit suscipit. Duis ante libero, auctor sed imperdiet ac, semper sit amet ligula. Nullam interdum nulla et libero hendrerit euismod.

In et ante ligula. Nulla nibh quam, feugiat vel molestie eu, luctus ut dolor. Nullam eu odio odio, id pharetra mauris. Donec quis enim at nunc gravida molestie. In hac habitasse platea dictumst. Aliquam pharetra massa id ipsum facilisis elementum. Nunc hendrerit, erat faucibus semper viverra, velit elit semper nulla, id tincidunt diam enim vel risus. Quisque tempus fringilla enim ut imperdiet. Donec gravida nibh id mauris accumsan vitae faucibus nisl malesuada.

Donec quam leo, condimentum ut pharetra sed, facilisis non lacus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum cursus interdum augue, at sagittis eros vestibulum sit amet. Nulla sed ipsum ipsum, id blandit dui. Etiam porttitor sem suscipit ipsum ultricies pharetra. Morbi a dapibus quam. Mauris fringilla, ipsum in cursus condimentum, erat urna volutpat enim, non volutpat libero lacus sit amet lacus. Vestibulum elementum gravida lacus quis tempus. Phasellus posuere est eu justo varius quis pharetra nulla ultricies.

Mauris adipiscing porta lorem et luctus. Nunc at dui risus, non malesuada mauris. Donec non purus erat. Phasellus a felis fermentum augue laoreet auctor et ac turpis. In posuere aliquam leo, quis iaculis metus laoreet in. Phasellus et odio nec ipsum lacinia tincidunt ac id justo. Vivamus tortor arcu, aliquet sit amet luctus ut, tempus pulvinar turpis. Sed tempor, felis vel dignissim ultrices, nulla orci egestas risus, in scelerisque turpis nunc ut felis. Quisque ultrices nisi vel tellus facilisis vestibulum rutrum leo rhoncus. Curabitur at magna risus, ac dapibus libero. Sed ut mauris eros.

Maecenas at tellus a tellus molestie suscipit. Cras sed dictum nisi. Nulla fringilla nulla a lacus placerat dapibus. Fusce sollicitudin, neque vitae placerat pharetra, lacus massa ullamcorper orci, aliquet adipiscing mi massa sed mi. Cras erat est, ornare eget lobortis ut, congue quis massa. Proin pellentesque, est vitae congue ullamcorper, magna est sagittis elit, in vehicula mauris justo ac augue. Praesent sed lorem elit. Cras convallis, elit eget laoreet rhoncus, sapien velit pharetra tellus, non porta nunc nunc sit amet ipsum. Fusce ante augue, euismod eu pellentesque eu, mattis sed turpis. In et turpis libero. Suspendisse potenti. Curabitur gravida nulla ut nunc gravida vitae ultrices turpis suscipit. Integer quis leo dui. Praesent consequat sollicitudin nibh ut egestas. Suspendisse placerat condimentum enim ac dignissim.

Etiam non viverra urna. Sed commodo consequat risus. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Cras lacinia dui feugiat diam tincidunt at molestie lorem dignissim. Ut vel elit arcu. Phasellus ut velit sem. In ut odio nisl, quis aliquam nisi.

Curabitur sed velit a mauris pretium scelerisque. Nam sed eros sed velit feugiat blandit. Etiam in metus nisl. Quisque faucibus leo molestie ligula dictum sollicitudin id et mauris. Proin pulvinar lacinia magna quis tempus. Donec gravida orci id metus facilisis euismod. Ut vitae justo lectus, sit amet sollicitudin velit. Aliquam sed elit sed leo molestie luctus. Mauris egestas rhoncus sapien, a rutrum erat pretium vel. Nullam blandit, velit convallis fermentum consequat, mauris augue fringilla metus, at dapibus dui lorem quis ante. Donec porta libero porta est sollicitudin bibendum id ut neque.

Maecenas ullamcorper placerat sapien sit amet venenatis. Aenean ut justo tortor, et euismod orci. Cras suscipit, neque vel ornare gravida, velit tellus vehicula dui, at pharetra neque sem a nunc. Aliquam magna leo, tristique ut cursus et, bibendum sed mi. Cras adipiscing magna eu leo lacinia eget gravida purus dictum. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Integer sit amet diam vel ipsum adipiscing laoreet mollis ut urna. Pellentesque eget libero eget lorem semper ultricies. Proin pharetra lacus vitae velit placerat luctus. Mauris et lacus mauris. Pellentesque convallis venenatis massa, nec hendrerit lorem imperdiet iaculis.

Proin nulla magna, gravida lobortis dignissim ac, dignissim vitae justo. Aenean non laoreet libero. Mauris felis risus, tempus ut imperdiet id, pharetra nec neque. Proin nibh nisl, faucibus nec laoreet nec, pulvinar a justo. Duis sollicitudin eleifend commodo. Morbi eu justo eros. Sed congue tellus nec urna porttitor dignissim. Curabitur enim nibh, accumsan a congue sit amet, elementum at tortor. Sed quis dignissim neque. Aenean justo est, bibendum quis tristique ac, vestibulum nec ipsum. Donec lacinia diam quis urna sagittis ac semper elit dictum. Praesent in eros nec ante hendrerit vehicula eu nec urna. Integer placerat felis sed arcu feugiat imperdiet. Vivamus tempor placerat hendrerit. Morbi sed sem risus.

Phasellus sollicitudin laoreet eleifend. Etiam mollis elementum est, id pharetra risus luctus quis. Donec ac dolor sapien. Duis a dolor vitae sapien varius suscipit ut a risus. Ut at mi erat. Fusce venenatis leo at enim luctus et vulputate metus varius. Morbi erat arcu, semper id eleifend vel, tincidunt id est. Nam sit amet nisl et tortor imperdiet volutpat. In mollis neque eget velit viverra id vulputate quam elementum. Proin ut metus neque. Suspendisse at arcu eget enim rutrum bibendum. Proin a quam ut ipsum varius pharetra ut rutrum sapien. Nullam nec est sapien, in consequat est. Phasellus dolor lorem, dapibus id luctus et, venenatis quis elit.

Aliquam a ipsum ut lacus dapibus posuere sed vel leo. Nulla rhoncus enim id urna lobortis fringilla. Praesent convallis, sapien ac accumsan malesuada, nulla augue eleifend quam, sit amet semper dui massa in mauris. Nulla facilisi. Vestibulum eget sagittis nulla. Sed nunc mauris, scelerisque id consequat vel, accumsan non neque. Vivamus pellentesque sollicitudin dui, eget varius orci vehicula sit amet. Quisque urna ligula, mollis sit amet varius a, tempor non ipsum. Donec vel diam mi.

Aliquam turpis purus, egestas eget ornare ac, vulputate at risus. Praesent convallis, quam fermentum laoreet consectetur, felis odio fermentum est, sit amet sodales nisl sapien quis lorem. Vivamus lacus metus, iaculis vel tincidunt quis, pretium vitae dolor. Mauris pellentesque mauris malesuada erat dictum non iaculis velit ultrices. Aliquam eleifend ornare metus rutrum molestie. Maecenas ac mi ut lorem porta molestie ut sit amet augue. Integer at nisi sit amet magna vestibulum laoreet ullamcorper a massa. Fusce in neque orci. Proin adipiscing eros a purus molestie eu sagittis ante condimentum. Etiam in urna ut nunc luctus venenatis. Aenean pharetra quam vitae eros adipiscing ut ultricies felis aliquet. In aliquet, arcu in aliquet bibendum, justo arcu ultrices augue, in dictum tortor arcu et dolor. Quisque elementum tortor quis nisl porta vitae hendrerit urna ultricies. Fusce egestas rutrum eros eu tincidunt. Sed quis odio at erat iaculis tincidunt. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos.

Ut ullamcorper mauris id velit congue semper. In odio metus, laoreet sed varius sed, gravida eget tortor. Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce adipiscing massa ac leo condimentum id congue dolor laoreet. Integer rutrum, urna a egestas facilisis, felis mi adipiscing felis, vitae interdum ligula ipsum vel metus. Aenean hendrerit pellentesque sollicitudin. Aliquam vestibulum magna sit amet orci mollis elementum.

Nam sed eros id sem dictum pellentesque. Donec id arcu risus, dapibus rutrum orci. Nulla varius ante sit amet erat hendrerit vel mollis orci congue. Integer cursus consectetur mauris eu aliquam. Aliquam mattis tortor venenatis ipsum dictum vel accumsan lectus sodales. Phasellus aliquam dignissim sagittis. Phasellus ornare hendrerit ligula, sed accumsan est volutpat sit amet. Donec a pulvinar metus. Vestibulum neque ante, varius sit amet tempus quis, consequat vitae orci. Sed vulputate commodo ligula rhoncus venenatis. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae;

Cras cursus rutrum ipsum, rhoncus venenatis nisi ullamcorper quis. Duis vel risus ac orci sodales aliquet sollicitudin ut justo. Pellentesque urna odio, tempor at ullamcorper ac, imperdiet non dolor. Sed bibendum velit tortor, ut euismod odio. Donec tristique ipsum id velit iaculis et vehicula odio imperdiet. Pellentesque interdum iaculis metus ut feugiat. Sed pretium diam iaculis lectus dapibus vestibulum vitae quis nisi. Cras placerat sem quis lacus tristique vel adipiscing diam porta. Morbi venenatis ultrices blandit. In facilisis sollicitudin cursus. In interdum, lorem in vehicula condimentum, nulla velit porttitor lacus, auctor tincidunt ligula eros non mi. Mauris nibh neque, vestibulum non sodales ut, congue sed sapien. Cras porttitor, lacus sit amet interdum sagittis, ipsum ante suscipit magna, quis facilisis ante nisi at sem. Vestibulum pulvinar lorem vulputate libero hendrerit vehicula. Etiam nisl sem, mollis et aliquam nec, tincidunt et purus.

In hac habitasse platea dictumst. Phasellus cursus diam gravida lectus molestie nec mattis sapien suscipit. Duis aliquet dapibus auctor. Proin pharetra imperdiet ullamcorper. Quisque nec ligula libero. Suspendisse vestibulum, lacus at dapibus viverra, lectus dolor auctor arcu, ultricies rhoncus diam orci id metus. Vestibulum id est arcu, quis eleifend dui. Duis sed justo eu nibh pharetra sagittis. Suspendisse potenti. Mauris dictum purus sit amet lacus faucibus posuere. Pellentesque vestibulum urna sed diam porttitor ac ultrices mauris pulvinar. Maecenas porta tincidunt fermentum. Nulla vitae pharetra sapien. Nullam sed ultrices dui.

Duis ultricies consequat luctus. Sed facilisis, metus eu rutrum posuere, orci leo bibendum nibh, non porttitor libero felis eget velit. Ut diam lorem, posuere sit amet condimentum non, mollis sit amet enim. Vivamus quis turpis tortor, id ultricies orci. Duis id risus metus, vel porttitor leo. Sed et vulputate leo. Aliquam ut sapien consequat nisi rutrum facilisis eu sed urna. Mauris imperdiet quam sed quam facilisis feugiat. Pellentesque ac tortor velit, id varius tellus. Aliquam nibh magna, accumsan varius blandit in, ultricies vitae tellus. Suspendisse non magna libero. Nulla urna ante, volutpat quis vulputate et, blandit euismod mi.

Sed ligula eros, placerat eu convallis vehicula, elementum non lectus. Duis dignissim nulla et leo tempus sollicitudin. Proin sagittis sodales dolor, vitae luctus elit bibendum non. Nulla facilisi. Nulla molestie laoreet ante et placerat. Suspendisse a risus nisl, sit amet egestas nulla. Fusce risus massa, imperdiet sit amet semper vitae, mattis et lacus. Ut quis risus sem, sit amet lacinia felis. Duis aliquam, nibh non consectetur laoreet, elit dolor egestas massa, non cursus nibh est at lectus. Aliquam sagittis lorem vitae lacus gravida sit amet facilisis tellus hendrerit.

Curabitur fermentum hendrerit nisl id consectetur. Ut ac tristique eros. Praesent ut urna est, ac auctor libero. Etiam sapien mauris, gravida ac gravida sit amet, iaculis ut libero. Praesent dolor nibh, cursus gravida dignissim vel, lobortis ac erat. Donec eu mattis metus. Proin sed elit quis lorem sodales placerat. Maecenas nec leo neque, a ornare ligula. Etiam ipsum quam, faucibus in fringilla ut, rhoncus a arcu. Morbi sagittis tempus nunc, id ultricies enim hendrerit nec. Donec vitae dolor sed dui condimentum aliquet. Curabitur sagittis aliquam rutrum. Mauris augue magna, pharetra non euismod vel, tempor eu felis. Fusce nec ante et tellus accumsan rutrum eu a massa. Nulla porta augue a mi facilisis auctor. Mauris a elit velit.
Generated 20 paragraphs, 1941 words, 12949 bytes of Lorem Ipsum
"
                };

            context.Specials.Add(Specials);
        }
    }
}